sudo: false
language: c
os:
  - linux

compiler:
#  - clang
  - gcc

script:
  - cd src
  - make
  - ./distprime 123400000000 123400500000 primes.log & ./distprimeworker 1 & ./distprimeworker 1
  - grep -F "123400000033" primes.log
  - grep -F "123400499977" primes.log
